<div class="container">
    <div class="row">
      <div class="col-sm-4 footer_left">
        1 Lomb Memorial Drive<br/>
        Rochester NY 14623
      </div>
      <div class="col-sm-4 footer_center">
      <a class="logo" href="index.php">
        <img class="footer_logo" src="img/clutch-cookie-logo.png" alt="Clutch Cookie"></a><br/>
        <a href="index.php">Order Online!
      </a><br/>
        <a href="cart.php">Your Cart</a>
      </div>
      <div class="col-sm-4 footer_right">
        Built By Athanasios Babasidis &copy; 2015 <br/>
        Rochester Institute of Technology <br/>
        ISTE 341
      </div>
    </div>
  </div>