<div class="row">
  <div class="col-sm-6">
    <a class="logo" href="index.php"><img class="logo_img" src="img/clutch-cookie-logo.png" alt="Clutch Cookie"></a>
  </div>
  <div class="col-sm-3">
    <div class="nav_link">
      <a href="index.php">Order Online!</a>
    </div>
  </div>
  <div class="col-sm-3">
    <div class="nav_link">
      <a href="cart.php">Your Cart</a>
    </div>
  </div>
  <hr/>
</div>
